os: osx
osx_image: xcode14.1

language: swift

branches:
  only:
    - master

script:
  - xcodebuild clean build -workspace MovieDB.xcworkspace -scheme MovieDB -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5'
