name: Build Xcode Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Xcode Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo Xcode-select -switch /Applications/Xcode_14.1.app


      - name: Build MovieDB
        run: |
         xcodebuild clean build -workspace MovieDB.xcworkspace -scheme MovieDB \
            -destination "generic/platform=iOS Simulator" \
            -derivedDataPath ".build"
